linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - execinquery
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gomnd
    - gomoddirectives
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - importas
    - ineffassign
    - intrange
    - lll
    - makezero
    - mirror
    - misspell
    - musttag
    - noctx
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - tenv
    - testableexamples
    - testifylint
    - testpackage
    #- thelper  # Too many false positives, no way to ignore.
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
linters-settings:
  gocyclo:
    min-complexity: 10
  godot:
    exclude:
      - Output:.*$
    period: true
    scope: all
  gomoddirectives:
    replace-local: true
  importas:
    no-extra-aliases: true
  lll:
    line-length: 80
    tab-width: 8
  tagliatelle:
    case:
      rules:
        avro: snake
        bson: camel
        env: upperSnake
        envconfig: upperSnake
        json: camel
        mapstructure: kebab
        toml: camel
        xml: camel
        yaml: camel
      use-field-name: true
run:
  modules-download-mode: readonly

