version: "2.1"
orbs:
  go: circleci/go@1.11.0
jobs:
  build:
    executor:
      name: go/default
      tag: "1.22.2"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: go test
          command: |
            set -x
            gotestsum --junitfile junit.xml -- \
              -timeout=1m -failfast -cover -race ./...
            set +x
      - store_test_results:
          path: junit.xml
workflows:
  main:
    jobs:
      - build
