// Code generated by "stringer -type Kind ."; DO NOT EDIT.

package apperror

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[UnknownError-1]
	_ = x[ValidationError-2]
	_ = x[UnauthorizedError-3]
	_ = x[ForbiddenError-4]
	_ = x[NotFoundError-5]
	_ = x[ConflictError-6]
	_ = x[PreconditionFailedError-7]
	_ = x[TooManyRequestsError-8]
	_ = x[TimeoutError-9]
}

const _Kind_name = "OKUnknownErrorValidationErrorUnauthorizedErrorForbiddenErrorNotFoundErrorConflictErrorPreconditionFailedErrorTooManyRequestsErrorTimeoutError"

var _Kind_index = [...]uint8{0, 2, 14, 29, 46, 60, 73, 86, 109, 129, 141}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
