// Code generated by "stringer -output rendering_mode_string.go -type RenderingMode ."; DO NOT EDIT.

package htmx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FullPage-0]
	_ = x[PartialUpdate-1]
}

const _RenderingMode_name = "FullPagePartialUpdate"

var _RenderingMode_index = [...]uint8{0, 8, 21}

func (i RenderingMode) String() string {
	if i < 0 || i >= RenderingMode(len(_RenderingMode_index)-1) {
		return "RenderingMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RenderingMode_name[_RenderingMode_index[i]:_RenderingMode_index[i+1]]
}
