# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:

permissions:
  contents: write
  actions: read
  checks: write

# Never cancel builds in main because it could disrupt releases.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.22"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: |
            go.sum
            x/eventlog/go.sum
            x/grpcerror/go.sum
            x/testlog/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58.1
          args: "--help" # Install the tool, but don't run it.

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Verify that generated files are up-to-date
        run: >
          ./regenerate.sh
          && git add .
          && git diff --quiet
          && git diff --cached --quiet
          || (git status; exit 1)

      - name: Build, test, and vet
        run: ./ok

      - name: Validate release tags
        if: github.ref != 'refs/heads/main'
        run: ./release-tags.sh verify

      - name: Create release tags
        if: github.ref == 'refs/heads/main'
        run: ./release-tags.sh create && git push --tags

      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Tests
          path: junit.xml
          reporter: java-junit
